services:
  backend:
    build: ./api
    container_name: backend
    env_file: .env
    ports:
      - "${API_PORT}:3000"
    networks:
      - app-network

  frontend:
    build: ./front
    container_name: frontend
    ports:
      - "${FRONT_PORT}:80"
    depends_on:
      - backend
    networks:
      - app-network

  bots:
    build:
      context: ./bots
    container_name: bots_service
    restart: always
    env_file:
      - .env
    volumes:
      - ./bots:/app
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
